#######################################################################
# NOME = JOÃO ALEXANDRE A. DE SA
# MATRICULA = 12211EAU020
# TRABALHO = ps-02-piso-escola
#######################################################################


# ATRIBUO QUE O VALOR DAS VARIAVEIS VAI SER INSERIDO PELO USUARIO

L = int(input())
C = int(input())

# DEFINO A AREA TOTAL DA FIGURA
AT = C*L

# DETERMINO A QUANTIDADE DE LAJOTAS DO TIPO 2 DA SEGUINTE FORMA:
# AS LAJOTAS DO TIPO 2 SÓ SE ENCONTRAM NAS LATERAIS E SÃO SEMPRE 1 A MENOS DO VALOR DO COMPRIMENTO E DA LARGURA
# DEPOIS DETERMINO QUE A ÁREA TOTAL OCUPADA PELAS LAJOTAS DO TIPO 2 MULTIPLICANDO O TOTAL DE LAJOTAS PELO VALOR
# INDIVIDUAL DE SUA ÁREA

LAJ2 = (C-1)*(2)+(L-1)*(2)
AT_LAJ2 = (LAJ2)*(1/4)

# DETERMINO A QUANTIDADE DE LAJOTAS DO TIPO 3 E A AREA TOTAL QUE OCUPAM
LAJ3 = 4
AT_LAJ3 = 0.5

# DETERMINO QUE A AREA RESTANTE É A SUBTRACAO DA AREA TOTAL PELAS AREAS TOTAIS DAS LAJOTAS 2 E 3
AR = (AT)-(AT_LAJ3)-(AT_LAJ2)

# DEFINO QUE A QUANTIDADE DE LAJOTAS DO TIPO 1 VAI SER A AREA RESTANTE DIVIDIDA PELA AREA DE UMA LAJOTA DO TIPO 1
LAJ1 = int((AR)/(1/2))

# PRINTO A QUANTIDADE DE LAJOTAS DO TIPO 1 E 2, RESPECTIVAMENTE
print(LAJ1)
print(LAJ2)

